Useful links:

-  

   #+BEGIN_QUOTE
     This document:
     [[https://docs.google.com/document/d/15tp-qCzhzwOA_BITVgnojZyE0bKoqWmzfZ1qgwC0XDQ/edit][/https://docs.google.com/document/d/15tp-qCzhzwOA\_BITVgnojZyE0bKoqWmzfZ1qgwC0XDQ/edit/]]
     or
     [[https://tinyurl.com/euxfel-wp4][/https://tinyurl.com/euxfel-wp4/]]
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     INDICO page:
     [[https://indico.desy.de/indico/event/23379/][/https://indico.desy.de/indico/event/23379//]]
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     Slack: [[https://panosc.slack.com][/https://panosc.slack.com/]]
     (request access from
     [[mailto:Jamie.hall@ill.eu][/Jamie.hall@ill.eu/]] or
     [[mailto:Hans.fangohr@xfel.eu][/Hans.fangohr@xfel.eu/]] for access)
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     Social media: Twitter @panosc\_eu, #PaNOSC
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     Present slides by
   #+END_QUOTE

   -  

      #+BEGIN_QUOTE
        Opening Chrome or Firefox
      #+END_QUOTE

   -  

      #+BEGIN_QUOTE
        Open [[https://appear.in/fangohr][/https://appear.in/fangohr/]]
      #+END_QUOTE

   -  

      #+BEGIN_QUOTE
        Mute your microphone (and speakers)
      #+END_QUOTE

   -  

      #+BEGIN_QUOTE
        Share your screen
      #+END_QUOTE

#+BEGIN_QUOTE
  Note: only 4 clients are allowed to connect (One is Jerome, one is the
  displaying machine, one is the speaker.).
#+END_QUOTE

* 25 June 2019
  :PROPERTIES:
  :CUSTOM_ID: june-2019
  :END:

Minutes (please all contribute ideas, concerns, questions, possible
designs, URLs, etc)

XTOB 1.108 has a kitchen & glasses

Emergency cooling (ice cream) available ~13.50

9:35 Andy Goetz

-  

   #+BEGIN_QUOTE
     WP4 is biggest work package
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     15% of project is over
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     Invited to present use cases at a future (name?) workshop
   #+END_QUOTE

   -  

      #+BEGIN_QUOTE
        Use cases not documented in the EC proposal
      #+END_QUOTE

   -  

      #+BEGIN_QUOTE
        Some use cases at
        [[https://github.com/panosc-eu/panosc/tree/master/Work%20Packages/WP4%20Data%20analysis%20services/resources][/https://github.com/panosc-eu/panosc/tree/master/Work%20Packages/WP4%20Data%20analysis%20services/resources/]]
      #+END_QUOTE

10:00 Hans Fangohr

-  

   #+BEGIN_QUOTE
     STFC 1 PB space - how to access
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     Amsterdam EGI meeting
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     Keep track of where data is moved to - more convenient locations -
     can this be done in data catalog?
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     Broad goals:
   #+END_QUOTE

   -  

      #+BEGIN_QUOTE
        Identify use cases for each institute
      #+END_QUOTE

   -  

      #+BEGIN_QUOTE
        Agree on the broad strokes for the infrastructure and solutions
        to use
      #+END_QUOTE

   -  

      #+BEGIN_QUOTE
        Propose and fix some more fine-grained internal milestones
      #+END_QUOTE

   -  

      #+BEGIN_QUOTE
        Ensure better co-operation between facilities
      #+END_QUOTE

   -  

      #+BEGIN_QUOTE
        Form small inter-facility teams amongst ourselves
      #+END_QUOTE

10:20 CERIC-ERIC Update - Carlos

-  

   #+BEGIN_QUOTE
     Marco from CERIC ERIC also here
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     Use cases:
   #+END_QUOTE

   -  

      #+BEGIN_QUOTE
        VUO + h5nuvola (web based hdf5 viewer
        [[https://github.com/ElettraSciComp/h5nuvola][/https://github.com/ElettraSciComp/h5nuvola/]]
        )
      #+END_QUOTE

   -  

      #+BEGIN_QUOTE
        H5nuvola on binder:
      #+END_QUOTE

      -  

         #+BEGIN_QUOTE
           Uses app mode (hiding cells, only shows widgets)
         #+END_QUOTE

      -  

         #+BEGIN_QUOTE
           Does things that hdfview does
         #+END_QUOTE

      -  

         #+BEGIN_QUOTE
           Demo:
           [[http://tinyurl.com/y3422mg8][/http://tinyurl.com/y3422mg8/]]
         #+END_QUOTE

   -  

      #+BEGIN_QUOTE
        VUO
      #+END_QUOTE

      -  

         #+BEGIN_QUOTE
           Management of experiment lifecycle
         #+END_QUOTE

      -  

         #+BEGIN_QUOTE
           Metada for experiment
         #+END_QUOTE

      -  

         #+BEGIN_QUOTE
           Remote access (via web)
         #+END_QUOTE

   -  

      #+BEGIN_QUOTE
        PyMCA (jupyter+remote desktop, Fitting x-ray powder diffraction
        (XRD), input from hd5, CLI and GUI) -
        [[http://pymca.sourceforge.net/][/http://pymca.sourceforge.net//]]
      #+END_QUOTE

   -  

      #+BEGIN_QUOTE
        PtyPy (jupyter, GPU enabled, io is hdf5) -
        [[https://ptycho.github.io/ptypy/][/https://ptycho.github.io/ptypy//]]
      #+END_QUOTE

-  

   #+BEGIN_QUOTE
     JupyterHub deployment under consideration
   #+END_QUOTE

   -  

      #+BEGIN_QUOTE
        Have a single notebook server for TwinMic beamline (X-ray
        microscopy)
      #+END_QUOTE

      -  

         #+BEGIN_QUOTE
           Kernels: Python2, Python 3, PtyPy + GPU
         #+END_QUOTE

-  

   #+BEGIN_QUOTE
     Users largely rely on the notebooks and services for the last
     steps, just the visualisation, not full data
     analysis/reduction/creation
   #+END_QUOTE

10:40 ELI Update - Jakub

-  

   #+BEGIN_QUOTE
     Recently hired extra person for PaNOSC
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     Interviewing for new WP3 position
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     Mariana, Eduard, Robert Racz
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     Notebook that creates XDMF file that can be presented by Paraview
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     Notebook to create files for visualisation, then use (hard-ware
     accelerated) visualisation software (Binary buffers direct to GPU
     for fast 3D visualisations)
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     Notebook use cases:
   #+END_QUOTE

   -  

      #+BEGIN_QUOTE
        Analytical modelling
      #+END_QUOTE

   -  

      #+BEGIN_QUOTE
        Simulation analysis (runs notebook on HPC)
      #+END_QUOTE

-  

   #+BEGIN_QUOTE
     First users in June 2019
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     200 to 400 TB estimated for 2019, multiple PB projected over next
     years
   #+END_QUOTE

10:48 ESRF Update - Thomas

-  

   #+BEGIN_QUOTE
     Shut down for year -
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     Old cluster for jupyter, DAAS
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     JupyterHubs
   #+END_QUOTE

   -  

      #+BEGIN_QUOTE
        Prototypes in use, one beamline does all data reduction and
        processing in Jupyter Hub
      #+END_QUOTE

   -  

      #+BEGIN_QUOTE
        Not visible from outside ESRF; will be fixed when new hardware
        and Kubernetes arrives (people use ssh port-forwarding for now)
      #+END_QUOTE

-  

   #+BEGIN_QUOTE
     Use cases:
   #+END_QUOTE

   -  

      #+BEGIN_QUOTE
        Goals: based on open source, have sample data
      #+END_QUOTE

   -  

      #+BEGIN_QUOTE
        1. PyNX
      #+END_QUOTE

      -  

         #+BEGIN_QUOTE
           Command line or Jupyter Notebook
         #+END_QUOTE

      -  

         #+BEGIN_QUOTE
           Need tools to visualise the data (3d or 2d cut planes)
         #+END_QUOTE

      -  

         #+BEGIN_QUOTE
           No 3d visualisation in notebook for now. [Hans: Try ipyvolume
           or k3d?]
         #+END_QUOTE

   -  

      #+BEGIN_QUOTE
        2. Cryspy
      #+END_QUOTE

      -  

         #+BEGIN_QUOTE
           Simulation of spectoscropy (Marius Retegan)
         #+END_QUOTE

      -  

         #+BEGIN_QUOTE
           Desktop application -> VISA
         #+END_QUOTE

   -  

      #+BEGIN_QUOTE
        PyFAI
      #+END_QUOTE

      -  

         #+BEGIN_QUOTE
           GUI for calibration, QT
         #+END_QUOTE

      -  

         #+BEGIN_QUOTE
           Aim to move selection into notebook
         #+END_QUOTE

   -  

      #+BEGIN_QUOTE
        Comment on Hardware: PyNX and PyFAI are meant to run on GPU.
        Problem, no GPU where the notebook is running, but notebook can
        spawn jobs on nodes with GPUs
      #+END_QUOTE

ESS Update - Lottie

-  

   #+BEGIN_QUOTE
     DMSC data centre
   #+END_QUOTE

   -  

      #+BEGIN_QUOTE
        Work on workflows
      #+END_QUOTE

   -  

      #+BEGIN_QUOTE
        Scipp (pronouce: skippy)
      #+END_QUOTE

   -  

      #+BEGIN_QUOTE
        Consider using DASK
      #+END_QUOTE

   -  

      #+BEGIN_QUOTE
        Sasview/ sasmodels
      #+END_QUOTE

   -  

      #+BEGIN_QUOTE
        McStas
      #+END_QUOTE

      -  

         #+BEGIN_QUOTE
           Neutron ray training simulation package
         #+END_QUOTE

      -  

         #+BEGIN_QUOTE
           Python generates meta file, translated to instrument, then
           run on cluster -> use Jupyter to create metalanguage file
         #+END_QUOTE

   -  

      #+BEGIN_QUOTE
        Qens: binderHub example
      #+END_QUOTE

-  

   #+BEGIN_QUOTE
     Status
   #+END_QUOTE

   -  

      #+BEGIN_QUOTE
        Jupyterhub instance running in dev network
      #+END_QUOTE

   -  

      #+BEGIN_QUOTE
        Kubernetes and LDAP
      #+END_QUOTE

   -  

      #+BEGIN_QUOTE
        BinderHub installation ongoing, issues with proxies
      #+END_QUOTE

-  

   #+BEGIN_QUOTE
     Staff: split between Kareem Galal , Lottie and New staff member
     starting 1 August.
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     Comment: Use rancher for kubernetes
   #+END_QUOTE

11:44 Report from EuXFEL (Robert)

-  

   #+BEGIN_QUOTE
     Notebook applications
   #+END_QUOTE

   -  

      #+BEGIN_QUOTE
        Karabo-data-interactive
      #+END_QUOTE

   -  

      #+BEGIN_QUOTE
        Geo-assembler -> link to KaraboFAI
      #+END_QUOTE

   -  

      #+BEGIN_QUOTE
        Warppipes for complex jobs
      #+END_QUOTE

   -  

      #+BEGIN_QUOTE
        Can track on SLURM if they don't know how to do batch jobs
      #+END_QUOTE

   -  

      #+BEGIN_QUOTE
        Run data calibration pipeline via notebook (Steffen's talk)
      #+END_QUOTE

-  

   #+BEGIN_QUOTE
     Tutorials for users (in notebook)
   #+END_QUOTE

   -  

      #+BEGIN_QUOTE
        General introduction
      #+END_QUOTE

   -  

      #+BEGIN_QUOTE
        Specific for a particular experiment
      #+END_QUOTE

      -  

         #+BEGIN_QUOTE
           Mix of tutorial and template
         #+END_QUOTE

-  

   #+BEGIN_QUOTE
     JupyterHUB
   #+END_QUOTE

   -  

      #+BEGIN_QUOTE
        Dev version allows picking template notebook (such as
        Python-Tutorial)
      #+END_QUOTE

11:54 Report from ILL (Jamie)

- JupyterHub

- in pilot phase

- BinderHub

#+BEGIN_QUOTE
  - not convinced people will use it

  - question: What barriers could be removed to make adoption more
  attractive? Proposal from the audience: Default
  container/requirements.txt; integration of Git(lab) with Jupyter (no
  need to learn about Git)

  - 4 people across WP3 and WP4

  - developing new RDP protocol, converting x server to WebGL + textures
  (not public yet)

  - working group of scientists
#+END_QUOTE

12:02 Report from WP5 (Carsten Fortmann-Grote)

-  

   #+BEGIN_QUOTE
     Developing an API layer for the users. Access via Jupyter
     Notebooks, Desktop applications, or other workflow managers (Knime,
     ...?)
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     Defining interfaces between different simulation steps
   #+END_QUOTE

   -  

      #+BEGIN_QUOTE
        [Should we use the same interfaces for data analysis? Ideally
        yes.]
      #+END_QUOTE

-  

   #+BEGIN_QUOTE
     Connection of simulation work in WP5 to WP4
   #+END_QUOTE

   -  

      #+BEGIN_QUOTE
        Produce data to feed into software
      #+END_QUOTE

   -  

      #+BEGIN_QUOTE
        Produce data to benchmark analysis algorithms
      #+END_QUOTE

   -  

      #+BEGIN_QUOTE
        Combined (iterative) data analysis schemes, using
        forward-reverse data analysis schemes
      #+END_QUOTE

-  

   #+BEGIN_QUOTE
     Data standards
   #+END_QUOTE

   -  

      #+BEGIN_QUOTE
        openPMD for physics
      #+END_QUOTE

      -  

         #+BEGIN_QUOTE
           [[http://www.openpmd.org][/www.openpmd.org/]]
         #+END_QUOTE

      -  

         #+BEGIN_QUOTE
           Standard format for simulations of particles and meshes
         #+END_QUOTE

      -  

         #+BEGIN_QUOTE
           Does parallel data
         #+END_QUOTE

   -  

      #+BEGIN_QUOTE
        NEXUS for detector data
      #+END_QUOTE

-  

   #+BEGIN_QUOTE
     Model based on ASE - Atomic Simulation Environment
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     Can we use simulation to provide data for analysis for our early
     prototypes (while real data cannot be moved)?
   #+END_QUOTE

-  

12:15 Lunch break

13:36 Report from WP3 (Gareth)

-  

   #+BEGIN_QUOTE
     /Seamless/ data catalog integration with EOSC
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     Link to use cases on slides
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     Data movement
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     Need some authentication/separate search to deal with embargoed
     data
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     Consult with scientists to find out what metadata needs to be
     tracked
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     PaNOSC API Draft - link on slides
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     Question from WP3 for WP4: what metadata do you need to be
     searchable?
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     Authentication is still being dealt with by WP6
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     EOSC is the portal, WP3 just provides the API to EOSC for the
     search
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     Catalogue search demonstrator portal is a deliverable for WP3
   #+END_QUOTE

   -  

      #+BEGIN_QUOTE
        Include links to fire up appropriate analysis
      #+END_QUOTE

   -  

      #+BEGIN_QUOTE
        Something to use as a prototype work between WP3 and WP4 at ESS?
      #+END_QUOTE

13:57 Report from WP6 (Jamie)

-  

   #+BEGIN_QUOTE
     SAML 2.0, ABFAB (Moonshot)
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     [[https://wiki.moonshot.ja.net/][/https://wiki.moonshot.ja.net//]]
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     EOSC Authentication , using Umbrella ID currently, will move to
     EDUTeams (Géant)
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     Ongoing evaluation for data transfer standard
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     EGI notebooks
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     Globus, rucio, FTS3 for data transfer
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     OneData
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     [[https://fts.web.cern.ch/][/https://fts.web.cern.ch//]]
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     [[https://rucio.cern.ch/][/https://rucio.cern.ch//]]
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     [[https://onedata.org/#/home][/https://onedata.org/#/home/]]
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     [[https://www.egi.eu/services/notebooks/][/https://www.egi.eu/services/notebooks//]]
   #+END_QUOTE

14:00 Report EGI (Giuseppe)

-  

   #+BEGIN_QUOTE
     Jupyter Notebooks ‘as a service' in the EGI Cloud:
     [[https://notebooks.egi.eu/hub/login][/https://notebooks.egi.eu/hub/login/]]
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     Builds on top of JupyterHub
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     ONEDATA
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     B2DROP
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     Reproduce results:
   #+END_QUOTE

   -  

      #+BEGIN_QUOTE
        Notebook, mounts data set through ONEDATA
      #+END_QUOTE

-  

   #+BEGIN_QUOTE
     Can generate PID
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     Install OneProvider
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     Caching available, but not by default
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     Location aware scheduling is not currently a feature. (is it on the
     roadmap?)
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     Pre stage the data? Sure, ask for it ahead of time
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     Make data available
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     Webdav as FlexVolume in k8s
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     Next steps:
   #+END_QUOTE

   -  

      #+BEGIN_QUOTE
        Move to production
      #+END_QUOTE

   -  

      #+BEGIN_QUOTE
        Deploy binder instance
      #+END_QUOTE

   -  

      #+BEGIN_QUOTE
        Test AAI check in
      #+END_QUOTE

14:15 Calipso Plus, VISA, towards a common Portal (Jamie, Aidan)

-  

   #+BEGIN_QUOTE
     Discussions
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     [[https://github.com/indigo-dc/udocker][/Udocker/]] - run docker
     containers (no fancy networking, not k8s compatible) without root
     permissions (M Crusoe)
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     ILL has screencasts explaining how data for an instrument is
     typically analysed
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     Common API
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     Discussion: avoid re-inventing the wheel
   #+END_QUOTE

   -  

      #+BEGIN_QUOTE
        M. Crusoe invites you all to join the wheel building and
        maintenance communities as you discover them :-)
      #+END_QUOTE

15:07 Break

15:30 Discussions:

[break out rooms available: XHQ 1.007 & XHQ E1.150 & XHQ E2.037]

17:00 Summary

17:30 Close

* Wednesday 26 June 2019
  :PROPERTIES:
  :CUSTOM_ID: wednesday-26-june-2019
  :END:

9:15 Welcome (Hans)

-  

   #+BEGIN_QUOTE
     Upload presentations to INDICO
     ([[https://indico.desy.de/indico/event/23379/][/https://indico.desy.de/indico/event/23379//]])
   #+END_QUOTE

9:15 Michael Crusoe: Common Workflow Language (CWL)

[[https://tinyurl.com/PaNOSC-CWL][/https://tinyurl.com/PaNOSC-CWL/]]

-  

   #+BEGIN_QUOTE
     C for Commonly used and Commonly implemented
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     Standard for describing
   #+END_QUOTE

   -  

      #+BEGIN_QUOTE
        Command line tools
      #+END_QUOTE

   -  

      #+BEGIN_QUOTE
        Workflows
      #+END_QUOTE

-  

   #+BEGIN_QUOTE
     May not have shared filesystem
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     Use on laptop and remote server
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     There are bad standards out there!
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     Discussion/examples:
   #+END_QUOTE

   -  

      #+BEGIN_QUOTE
        Do not pass around paths, it's not portable
      #+END_QUOTE

   -  

      #+BEGIN_QUOTE
        Containers are supported but don't have to be used
      #+END_QUOTE

-  

   #+BEGIN_QUOTE
     Workflow approach vs notebook approach
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     Provenance! Show where data comes from - verify results
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     YAML since you can have comments, not in JSON!
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     CWL model for tools
   #+END_QUOTE

   -  

      #+BEGIN_QUOTE
        Turns POSIX command-line tools into functions
      #+END_QUOTE

   -  

      #+BEGIN_QUOTE
        Typed input and output
      #+END_QUOTE

-  

   #+BEGIN_QUOTE
     Hardware description available (#cores, memory, temporary and
     output storage estimations)
   #+END_QUOTE

   -  

      #+BEGIN_QUOTE
        -> can use for PaNOSC to extend Binder specification to support
        hardware requirements?
      #+END_QUOTE

   -  

      #+BEGIN_QUOTE
        GPUs requirements not included.
      #+END_QUOTE

-  

   #+BEGIN_QUOTE
     Data locality with CWL
   #+END_QUOTE

   -  

      #+BEGIN_QUOTE
        URI/IRI
      #+END_QUOTE

-  

   #+BEGIN_QUOTE
     Community based standards development
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     ResearchObject.org - helps with provenance
   #+END_QUOTE

   -  

      #+BEGIN_QUOTE
        Intro
      #+END_QUOTE

      -  

         #+BEGIN_QUOTE
           EOSC all about re-use of tools
         #+END_QUOTE

      -  

         #+BEGIN_QUOTE
           Customise for the customers relevant
         #+END_QUOTE

   -  

      #+BEGIN_QUOTE
        Just a json file ...
      #+END_QUOTE

   -  

      #+BEGIN_QUOTE
        Raw data is never fair
      #+END_QUOTE

      -  

         #+BEGIN_QUOTE
           Where is identifier (?)
         #+END_QUOTE

      -  

         #+BEGIN_QUOTE
           Where is provenance
         #+END_QUOTE

      -  

         #+BEGIN_QUOTE
           Where is attribution?
         #+END_QUOTE

   -  

      #+BEGIN_QUOTE
        Recommends to checkout openarchive (?)
      #+END_QUOTE

-  

   #+BEGIN_QUOTE
     How much can you trust results from this process?
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     Biocompute objects
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     Are you just writing scripts or have standalone tools?
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     Are you packaging and containerising the tools?
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     Users rarely reuse workflows without making changes; different
     tools, parameters
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     Where do manifests get persisted?
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     It's your choice
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     [[http://www.researchobject.org/ro2019/][/http://www.researchobject.org/ro2019//]]
   #+END_QUOTE

   -  

      #+BEGIN_QUOTE
        Tuesday 24 September 2019 (2019-09-24)
      #+END_QUOTE

   -  

      #+BEGIN_QUOTE
        2019-07-05 RO2019 submissions due: articles
      #+END_QUOTE

   -  

      #+BEGIN_QUOTE
        2019-07-15 RO2019 submissions due: abstracts for oral
        presentation
      #+END_QUOTE

-  

   #+BEGIN_QUOTE
     Workshop on Research Objects (RO2019) At IEEE eScience 2019, San
     Diego, CA
   #+END_QUOTE

-  

10:00 Anton Barty: ExPaNDS Project

-  

   #+BEGIN_QUOTE
     750 TB in 5 days
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     |Don't want to mess around
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     Science is not in computing is in the results
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     Don't want to be told there is a new API and rewrite software
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     Shouldn't have to repeat experiment unless you want to
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     Archive beamline scientists for every experiment for full
     reproducibility
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     Kickoff meeting 11 and 12 September
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     Electronic logbook
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     Google sheets as electronic logbook
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     Confluence as electronic logbook
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     Need for better online logbooks
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     User education
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     Google spreadsheet is more compelling
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     Snap a photo on your tablet and upload it
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     ESRF is preparing electronic logbook
   #+END_QUOTE

10:20 Michael Schuh (DESY IT)

-  

   #+BEGIN_QUOTE
     Function as a service here means container as a function
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     Kafka, Apache Openwhisk to manage scaling
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     If no-one uses this function it doesn't block memory
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     Chain the containers
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     Upload a lot of files to dCache it automatically sends message to
     Kafka queue and open whisk produces a visualisation for each file
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     “Git-ops”: put everything into git, you just push, everything else
     is built (and deployed?)
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     Keeps everything stateless, so it is portable (not mounting file
     systems, but use webdav)
   #+END_QUOTE

11:50 Robert Rosca - Review of computational portal (workflow tools?)

-  

   #+BEGIN_QUOTE
     CodeOcean
   #+END_QUOTE

   -  

      #+BEGIN_QUOTE
        [[https://codeocean.com/][/https://codeocean.com//]]
      #+END_QUOTE

   -  

      #+BEGIN_QUOTE
        Jupyterlab
      #+END_QUOTE

   -  

      #+BEGIN_QUOTE
        Costs money - but good template
      #+END_QUOTE

-  

   #+BEGIN_QUOTE
     DAGsHUB
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     DVC - Data Version Control
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     Wholetale
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     Hubzero.org
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     ...
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     Michael Crusoe mentions: [[https://galaxyproject.org/][/galaxy
     platform/]] that combines it all, is open source, has been around
     for 10 years, and has an annual conference . Mostly bio, but very
     'customizable for other communities.
   #+END_QUOTE

   -  

      #+BEGIN_QUOTE
        Video demo of interactive environments
        [[https://www.youtube.com/watch?v=OOrCUYj3Pok][/https://www.youtube.com/watch?v=OOrCUYj3Pok/]]
      #+END_QUOTE

Next WP4 meeting

Should be every 4-6 months

Hackathons

Working meeting

ILL can host next meeting

ESS following meeting

Jamie has licence for confluence

Confluence.panosc.eu

Rooms available 26 June

-  

   #+BEGIN_QUOTE
     E1.041 (11:30 to 15:30)
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     R2.042 (11:30 to 14:00)
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     E1.150 (after 12:00)
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     E2.148 (after 15:00)
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     E2.037 (all day)
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     XTOB1.01 (after 11:00)
   #+END_QUOTE

13:30 Notebooks in use (Scientists from EuXFEL, Steffen Hauf)

-  

   #+BEGIN_QUOTE
     Offline calibration at XFEL
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     Remove calibration detector peculiarities
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     Corrected and calibrated data is the main product
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     Produce correction parameters
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     Manage correction parameters
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     Optimise corrections
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     Python - fast development cycles - good data analysis
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     pyCalibrate
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     Calibration web service
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     Configuration via yaml files
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     Defined in notebook - automatically propagate
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     CLI
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     Produce pdf reports
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     Expect Usage
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     Monitoring
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     Anything in notebook will be rendered into pdf
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     AGIPD LPD DSSC
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     Complex reports, over 100 pages
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     24 production notebooks
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     30k SLURM jobs
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     15 minutes
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     Heatmap plots don\t convert well from SVG to pdf/png
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     Tabular output doesn't render well in pdf
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     RST and HTML same
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     1.5 years development
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     Use case: “I see something on detector I don't understand”
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     “Interact with notebook to determine cause”
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     nbparametrise()
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     Why use notebook over normal python?
   #+END_QUOTE

   -  

      #+BEGIN_QUOTE
        Good for ongoing development
      #+END_QUOTE

   -  

      #+BEGIN_QUOTE
        Allows data-experts to contribute even if they are not confident
        programmers
      #+END_QUOTE

   -  

      #+BEGIN_QUOTE
        From interactively developed notebook to a scriptable notebook
        is often just some tidying up
      #+END_QUOTE

   -  

-  

   #+BEGIN_QUOTE
     [[https://github.com/jupyter/nbdime][/https://github.com/jupyter/nbdime/]]
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     Nbdiff notebooks; no known gitlab integration
   #+END_QUOTE

13:45 Notebooks in use (Scientists from EuXFEL, MID, Mario)

-  

   #+BEGIN_QUOTE
     Software deployment
   #+END_QUOTE

   -  

      #+BEGIN_QUOTE
        Install into proposal folder a conda distribution (tailored for
        the experiment)
      #+END_QUOTE

   -  

      #+BEGIN_QUOTE
        Also provide same examples (in notebooks) how to read and
        display and analysise data
      #+END_QUOTE

   -  

      #+BEGIN_QUOTE
        Also provide sample data
      #+END_QUOTE

-  

   #+BEGIN_QUOTE
     Why using Jupyter Notebooks?
   #+END_QUOTE

   -  

      #+BEGIN_QUOTE
        1. Persistent and interactive notebooks
      #+END_QUOTE

      -  

         #+BEGIN_QUOTE
           Better than Matlab: figure not inline in Matlab
         #+END_QUOTE

   -  

      #+BEGIN_QUOTE
        2. Code, Figures and Markdown
      #+END_QUOTE

      -  

         #+BEGIN_QUOTE
           Headings
         #+END_QUOTE

      -  

         #+BEGIN_QUOTE
           Explanations
         #+END_QUOTE

   -  

      #+BEGIN_QUOTE
        3. Extensions
      #+END_QUOTE

      -  

         #+BEGIN_QUOTE
           Table of contents
         #+END_QUOTE

      -  

         #+BEGIN_QUOTE
           Heading / code folding
         #+END_QUOTE

      -  

         #+BEGIN_QUOTE
           Snippets, ...
         #+END_QUOTE

   -  

      #+BEGIN_QUOTE
        4. Running in a browser and easy to use (with Jupyter Hub)
      #+END_QUOTE

-  

   #+BEGIN_QUOTE
     Use cases at MID
   #+END_QUOTE

   -  

      #+BEGIN_QUOTE
        Tutorial, with table of contents, with folding of (numbered)
        headings
      #+END_QUOTE

      -  

         #+BEGIN_QUOTE
           Initialisation cells to create required variables and
           functions
         #+END_QUOTE

   -  

      #+BEGIN_QUOTE
        As an e-log
      #+END_QUOTE

      -  

         #+BEGIN_QUOTE
           [Long notebook]
         #+END_QUOTE

   -  

      #+BEGIN_QUOTE
        Tried online visualisation in the last experiment (update from
        data stream automatically)
      #+END_QUOTE

-  

   #+BEGIN_QUOTE
     Issues
   #+END_QUOTE

   -  

      #+BEGIN_QUOTE
        Performance issues with large notebooks
      #+END_QUOTE

      -  

         #+BEGIN_QUOTE
           Slow to scroll, table of contents helps
         #+END_QUOTE

   -  

      #+BEGIN_QUOTE
        Notebooks can only be used by one user at a time
      #+END_QUOTE

   -  

      #+BEGIN_QUOTE
        Connection issues and output issues
      #+END_QUOTE

   -  

      #+BEGIN_QUOTE
        Interactive figures can be slow and provide only basic
        functionality
      #+END_QUOTE

      -  

         #+BEGIN_QUOTE
           Cannot click on line to change colour
         #+END_QUOTE

      -  

         #+BEGIN_QUOTE
           Cannot click on data in the figure
         #+END_QUOTE

   -  

      #+BEGIN_QUOTE
        Notebooks are lacking file system control and browsing features
      #+END_QUOTE

-  

   #+BEGIN_QUOTE
     Questions
   #+END_QUOTE

   -  

      #+BEGIN_QUOTE
        500 MB notebook limit for jupyterhub
      #+END_QUOTE

14:41 Notebooks in use (Scientists from EuXFEL, SCS, Laurent)

-  

   #+BEGIN_QUOTE
     Main advantage: flexibility to diagnose problems in realtime, based
     on existing (non-trivial) analysis notebooks
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     Snippet
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     Import snippets
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     Tedious to configure snippets
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     Have to add in json file
   #+END_QUOTE

-  

15:45 Discussion: -> Break out groups Wednesday

19:00 Workshop dinner

* 
  :PROPERTIES:
  :CUSTOM_ID: section
  :END:

* Thursday
  :PROPERTIES:
  :CUSTOM_ID: thursday
  :END:

9:00 Breakfast coffee

9:30 Visualisation tools and hdf5 (Thomas Vincent)

-  

   #+BEGIN_QUOTE
     Nexus
   #+END_QUOTE

   -  

      #+BEGIN_QUOTE
        ESRF uses NeXus through the entire data file - raw data,
        calibrated, processed, all conform to the NeXus standard
      #+END_QUOTE

   -  

      #+BEGIN_QUOTE
        nexusformat.org
      #+END_QUOTE

   -  

      #+BEGIN_QUOTE
        Use at Sardana as well as ESRF
      #+END_QUOTE

   -  

      #+BEGIN_QUOTE
        NXxas as an application definition, some flawed design choices
        with instrument naming conventions -
        [[http://download.nexusformat.org/doc/html/classes/applications/NXxas.html][/http://download.nexusformat.org/doc/html/classes/applications/NXxas.html/]]
      #+END_QUOTE

   -  

      #+BEGIN_QUOTE
        Application definitions should come from developers or
        communities otherwise useless ...
      #+END_QUOTE

   -  

      #+BEGIN_QUOTE
        NeXus also stores the program which was used and its version,
        and it can store the workflow and configuration so that you can
        use the NeXus metadata to reproduce the processing used to
        generate the data
      #+END_QUOTE

   -  

      #+BEGIN_QUOTE
        Can use NxNote for config storage
      #+END_QUOTE

-  

   #+BEGIN_QUOTE
     ESRF uses ICAT for their metadata catalogue
   #+END_QUOTE

   -  

      #+BEGIN_QUOTE
        To map NEXUS application type
      #+END_QUOTE

   -  

      #+BEGIN_QUOTE
        to categories in ICAT
      #+END_QUOTE

-  

   #+BEGIN_QUOTE
     [[http://www.esrf.eu/computing/bliss/doc/bliss/][/http://www.esrf.eu/computing/bliss/doc/bliss//]]
     - BeamLine Instrumentation Support Software
   #+END_QUOTE

   -  

      #+BEGIN_QUOTE
        REDIS + memcached
      #+END_QUOTE

   -  

      #+BEGIN_QUOTE
        Storing online data until memory is full?
      #+END_QUOTE

   -  

      #+BEGIN_QUOTE
        Provenance done via NXprocess
      #+END_QUOTE

-  

   #+BEGIN_QUOTE
     SILX view application understands the NeXus format
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     Capable of generating some plots based on the type of the data and
     the metadata
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     Attributes (metadata) and the name of the dataset/group is used to
     specify what the data is, can cause problems with naming
     conflicts/changes in the future
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     Requirements:
   #+END_QUOTE

   -  

      #+BEGIN_QUOTE
        Faster pan/zoom interaction
      #+END_QUOTE

   -  

      #+BEGIN_QUOTE
        Users changing colour maps, normalization, ranges, etc...
      #+END_QUOTE

   -  

      #+BEGIN_QUOTE
        Masking
      #+END_QUOTE

   -  

      #+BEGIN_QUOTE
        ROI and profile selection
      #+END_QUOTE

   -  

      #+BEGIN_QUOTE
        Better interactive plotting for large images (30k x 30k, 12G
        pixels)
      #+END_QUOTE

   -  

      #+BEGIN_QUOTE
        Better 3D plotting
      #+END_QUOTE

10:00 Virtual hdf5 data sets, h5glance and h5py (Thomas Kluyver)

-  

   #+BEGIN_QUOTE
     H5glance
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     Started with h5ls -rv - wall of text
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     H5view slow with x-forwarding
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     H5glance
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     Nicer way to look at files
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     Pasteable link into jupyter notebook
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     Low level h5py close to C API
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     Virtual datasets
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     Composed of pointers to other datasets
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     Exciting!
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     Use case - big detectors - each writes to separate file
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     Sequence files - cuts off sequence and starts a new one!
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     64 files in a run from one detector
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     Can be exposed as one massive array
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     Cxi 12 MB pointers to 190,000 images
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     Convenient interface
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     Q: Does h5copy copy actual data from virtual datasets?
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     Q: EuXFEL specific: when data for a module for a train is missing,
     how does the virtual data set (or the tool that creates the virtual
     data set) deal with this?
   #+END_QUOTE

[[https://indico.esrf.fr/indico/event/33/overview][/https://indico.esrf.fr/indico/event/33/overview/]]

10:30 Deployment of computational environments (Robert Rosca)

-  

   #+BEGIN_QUOTE
     Robert describes script-based creation of computational
     environments
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     [[https://spack.io/][/https://spack.io//]]
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     Manages versions of e.g. hdf5 and dependencies versions
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     Flatpack?
   #+END_QUOTE

   -  

      #+BEGIN_QUOTE
        ESRF:
      #+END_QUOTE

      -  

         #+BEGIN_QUOTE
           use debian packages, provide nightly builds
         #+END_QUOTE

      -  

         #+BEGIN_QUOTE
           Python virtual environments
         #+END_QUOTE

      -  

         #+BEGIN_QUOTE
           Use miniconda to install applications
         #+END_QUOTE

      -  

         #+BEGIN_QUOTE
           Using ‘module' as well
         #+END_QUOTE

   -  

      #+BEGIN_QUOTE
        Thomas mentions: Binderhub as another option
      #+END_QUOTE

   -  

      #+BEGIN_QUOTE
        Michael C mentions: GUIX
      #+END_QUOTE

      -  

         #+BEGIN_QUOTE
           Some facilities/communities make Debian packages installed
           natively or access via software containers
         #+END_QUOTE

   -  

      #+BEGIN_QUOTE
        [[https://www.softwareheritage.org/][/https://www.softwareheritage.org//]]
      #+END_QUOTE

   -  

      #+BEGIN_QUOTE
        ESS: for C++ use Conan
        [[https://conan.io/][/https://conan.io//]], for node npm, and
        python pip
      #+END_QUOTE

   -  

      #+BEGIN_QUOTE
        ESS config with Ansible
        [[https://www.ansible.com/][/https://www.ansible.com//]] and
        Puppet [[https://puppet.com/][/https://puppet.com//]], Docker
        for integration testing
      #+END_QUOTE

   -  

      #+BEGIN_QUOTE
        Mirrors (archives):
      #+END_QUOTE

      -  

         #+BEGIN_QUOTE
           Software heritage
         #+END_QUOTE

   -  

      #+BEGIN_QUOTE
        DESY: on the cloud
      #+END_QUOTE

      -  

         #+BEGIN_QUOTE
           Puppet modules
         #+END_QUOTE

   -  

      #+BEGIN_QUOTE
        Soleil: using Maven
      #+END_QUOTE

11:30 JupyterHub & BinderHub experience (Frank Schluenzen)

-  

   #+BEGIN_QUOTE
     HPC
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     Choose node on scheduler (SLURM,
     [[https://slurm.schedmd.com/documentation.html][/https://slurm.schedmd.com/documentation.html/]])
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     Choose GPU
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     Choose number of nodes
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     Pick notebook/jupyter lab/binder repository
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     Spawn
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     Build conda environment in memory and setup notebook, if only one
     notebook launch automatically else see multiple notebooks in file
     manager
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     /dev/shm is where it is actually taking place (not persistent,
     modify but won't change, need to export)
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     $ scontrol show job $SLURM\_ID
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     Can see details of job and number of cores
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     If i want a different repository - always go back to same page
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     16 nodes, infiniband, FhGFS
     ([[https://www.beegfs.io/][/https://www.beegfs.io/]])
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     25k cores
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     200+ GPU
   #+END_QUOTE

-  
-  

   #+BEGIN_QUOTE
     EOSC cloud
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     JupyterHub on Maxwell
   #+END_QUOTE

   -  

      #+BEGIN_QUOTE
        3 AMB nodes for jupyter jobs, 32(x2) cores per node, 256GB RAM,
        allow 32 concurrent jobs per node
      #+END_QUOTE

   -  

      #+BEGIN_QUOTE
        ~180 unique users in May 2019, ~15% of total number of users
      #+END_QUOTE

   -  

      #+BEGIN_QUOTE
        Comparable with Matlab usage now
      #+END_QUOTE

-  

   #+BEGIN_QUOTE
     Performance issues
   #+END_QUOTE

   -  

      #+BEGIN_QUOTE
        Notebooks don't need much CPU time
      #+END_QUOTE

   -  

      #+BEGIN_QUOTE
        But lots of RAM
      #+END_QUOTE

   -  

      #+BEGIN_QUOTE
        Dev version available in
        [[https://max-jhub003.desy.de][/https://max-jhub003.desy.de/]]
      #+END_QUOTE

-  

   #+BEGIN_QUOTE
     Packer ([[https://packer.io/][/https://packer.io//]]) for Openstack
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     Loadbalancer as a service
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     Hashcorp Terraform
     ([[https://www.terraform.io/][/https://www.terraform.io//]])
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     Kubespray (terraform + ansible)
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     Cinder storage class
   #+END_QUOTE

-  

13:30 Discussion and planning

-  

   #+BEGIN_QUOTE
     Rooms available:
   #+END_QUOTE

   -  

      #+BEGIN_QUOTE
        E2.037: Robert: Use case discussion and gathering. Desired
        outcome:
      #+END_QUOTE

      -  

         #+BEGIN_QUOTE
           Create list of use cases (notebook and other) [in this file
           or on github/../wp4]
         #+END_QUOTE

      -  

         #+BEGIN_QUOTE
           Some useful items of information/attributes:
         #+END_QUOTE

         -  

            #+BEGIN_QUOTE
              Title of use case
            #+END_QUOTE

         -  

            #+BEGIN_QUOTE
              Which facility
            #+END_QUOTE

         -  

            #+BEGIN_QUOTE
              Where is the analysis script?
            #+END_QUOTE

         -  

            #+BEGIN_QUOTE
              Data small(ish)?
            #+END_QUOTE

         -  

            #+BEGIN_QUOTE
              Data public?
            #+END_QUOTE

         -  

            #+BEGIN_QUOTE
              Scientist who cares about this (and can provide expert
              advice)
            #+END_QUOTE

         -  

            #+BEGIN_QUOTE
              Hardware requirements and approximate execution time
            #+END_QUOTE

   -  

      #+BEGIN_QUOTE
        To do:
      #+END_QUOTE

      -  

         #+BEGIN_QUOTE
           Change structure on git page
         #+END_QUOTE

         -  

            #+BEGIN_QUOTE
              Folder for scripts, (small) data(?), notebooks
            #+END_QUOTE

         -  

            #+BEGIN_QUOTE
              Screenshots of desktop applications
            #+END_QUOTE

         -  

            #+BEGIN_QUOTE
              List of scientists
            #+END_QUOTE

         -  

            #+BEGIN_QUOTE
              Special requirements like gpus, matlab, etc...
            #+END_QUOTE

         -  

            #+BEGIN_QUOTE
              Share tutorials or templates given to users
            #+END_QUOTE

         -  

            #+BEGIN_QUOTE
              Look at facility documentation to gather uses?
            #+END_QUOTE

      -  

         #+BEGIN_QUOTE
           *Use the shared data hosting for the example data STFC*
         #+END_QUOTE

      -  

         #+BEGIN_QUOTE
           Facility use cases:
         #+END_QUOTE

         -  

            #+BEGIN_QUOTE
              CERIC-ERIC
            #+END_QUOTE

            -  

               #+BEGIN_QUOTE
                 VUO, h5nuvola, PtyPy, PyMCA tutorial
               #+END_QUOTE

            -  

               #+BEGIN_QUOTE
                 H5nuvola demo:
                 [[http://tinyurl.com/y3422mg8][/http://tinyurl.com/y3422mg8/]]
               #+END_QUOTE

            -  

               #+BEGIN_QUOTE
                 Request facility data (to be added)
               #+END_QUOTE

            -  

               #+BEGIN_QUOTE
                 [[http://www.silx.org/doc/PyMca/dev/tutorials.html][/http://www.silx.org/doc/PyMca/dev/tutorials.html/]]
               #+END_QUOTE

         -  

            #+BEGIN_QUOTE
              ELI
            #+END_QUOTE

            -  

               #+BEGIN_QUOTE
                 TBA
               #+END_QUOTE

            -  

               #+BEGIN_QUOTE
                 Analytical modelling
               #+END_QUOTE

            -  

               #+BEGIN_QUOTE
                 Simulation analysis (runs notebook on HPC)
               #+END_QUOTE

            -  

               #+BEGIN_QUOTE
                 See Jakub presentation
               #+END_QUOTE

         -  

            #+BEGIN_QUOTE
              ESRF
            #+END_QUOTE

            -  

               #+BEGIN_QUOTE
                 [[https://github.com/panosc-eu/panosc/blob/master/Work%20Packages/WP4%20Data%20analysis%20services/use_cases/ESRF-use-cases.rst][/Already
                 on git page/]]
               #+END_QUOTE

            -  

               #+BEGIN_QUOTE
                 [[http://ftp.esrf.fr/pub/scisoft/PyNX/example_notebooks/CDI-Siemens%20star.html][/http://ftp.esrf.fr/pub/scisoft/PyNX/example\_notebooks/CDI-Siemens%20star.html/]]
               #+END_QUOTE

            -  

               #+BEGIN_QUOTE
                 Needs GPU!
               #+END_QUOTE

            -  

               #+BEGIN_QUOTE
                 pyFAI best with GPU
               #+END_QUOTE

            -  

               #+BEGIN_QUOTE
                 Simulations
               #+END_QUOTE

            -  

               #+BEGIN_QUOTE
                 [[https://gitlab.esrf.fr/paleo/sidi/blob/master/examples/distributed_fbp.ipynb][/https://gitlab.esrf.fr/paleo/sidi/blob/master/examples/distributed\_fbp.ipynb/]]
               #+END_QUOTE

            -  

               #+BEGIN_QUOTE
                 Notebook submits to cluster, need OAR/SLURM
               #+END_QUOTE

         -  

            #+BEGIN_QUOTE
              ESS
            #+END_QUOTE

            -  

               #+BEGIN_QUOTE
                 Mantid/scipp - python script + desktop app
               #+END_QUOTE

            -  

               #+BEGIN_QUOTE
                 SasView is desktop app
               #+END_QUOTE

            -  

               #+BEGIN_QUOTE
                 https://www.sasview.org/downloads/OldTutorial.pdf
               #+END_QUOTE

            -  

               #+BEGIN_QUOTE
                 QENS - notebook
               #+END_QUOTE

            -  

               #+BEGIN_QUOTE
                 [[https://github.com/QENSlibrary/QENSmodels/tree/master/examples-binder][/https://github.com/QENSlibrary/QENSmodels/tree/master/examples-binder/]]
               #+END_QUOTE

         -  

            #+BEGIN_QUOTE
              ILL
            #+END_QUOTE

            -  

               #+BEGIN_QUOTE
                 VISA (TBA)
               #+END_QUOTE

         -  

            #+BEGIN_QUOTE
              XFEL - see presentations
            #+END_QUOTE

            -  

               #+BEGIN_QUOTE
                 [[https://in.xfel.eu/readthedocs/][/https://in.xfel.eu/readthedocs//]]
               #+END_QUOTE

            -  

               #+BEGIN_QUOTE
                 [[https://in.xfel.eu/readthedocs/docs/data-analysis-user-documentation/en/latest/][/https://in.xfel.eu/readthedocs/docs/data-analysis-user-documentation/en/latest//]]
               #+END_QUOTE

      -  

         #+BEGIN_QUOTE
           [[https://github.com/panosc-eu/panosc/tree/master/Work%20Packages/WP4%20Data%20analysis%20services/use_cases][/https://github.com/panosc-eu/panosc/tree/master/Work%20Packages/WP4%20Data%20analysis%20services/use\_cases/]]
         #+END_QUOTE

      -  

   -  

      #+BEGIN_QUOTE
        XHQ: E2.062 Hans/Jamie Overall design: Amsterdam plan /
        BinderHub / role of portal plan, milestones
      #+END_QUOTE

   -  

      #+BEGIN_QUOTE
        XHQ: E2.148?
      #+END_QUOTE

-  

   #+BEGIN_QUOTE
     Improving Jupyter ecosystem [Robert Rosca]
   #+END_QUOTE

   -  

      #+BEGIN_QUOTE
        Reproducibility, plotting, dashboards, interactivity
      #+END_QUOTE

15:00 Summary

15:30 Coffee and close

16:00-17:00 XFEL tour

* Break out groups
  :PROPERTIES:
  :CUSTOM_ID: break-out-groups
  :END:

* Tuesday
  :PROPERTIES:
  :CUSTOM_ID: tuesday
  :END:

-  

   #+BEGIN_QUOTE
     XHQ E1.150: Hans/Jamie Overall design: Amsterdam plan / BinderHub /
     role of portal plan, milestones
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     XHQ E1.007: Aidan JupyterHub Deployment - technical aspects
   #+END_QUOTE

   -  

      #+BEGIN_QUOTE
        Different spawners - batch, kube, sudo
      #+END_QUOTE

   -  

      #+BEGIN_QUOTE
        Binderhub, repo2docker, zero2jupyterhub
      #+END_QUOTE

   -  

      #+BEGIN_QUOTE
        [[https://github.com/jupyterhub/batchspawner/issues/138#issuecomment-501790720][/https://github.com/jupyterhub/batchspawner/issues/138#issuecomment-501790720/]]
      #+END_QUOTE

   -  

      #+BEGIN_QUOTE
        [[https://docs.google.com/document/d/1_oeCBMvo6zW5DMeFHCmjQy-Eq2bQO9Q1DekT4laY27A][/https://docs.google.com/document/d/1\_oeCBMvo6zW5DMeFHCmjQy-Eq2bQO9Q1DekT4laY27A/]]
      #+END_QUOTE

-  

   #+BEGIN_QUOTE
     XHQ E2.037: Thomas Vincent Visualisation (and Hdf5 visualisation)
     -> can we converge / re-use?
   #+END_QUOTE

* Wednesday
  :PROPERTIES:
  :CUSTOM_ID: wednesday
  :END:

Break out groups at break + 30 minutes (~15:30)

-  

   #+BEGIN_QUOTE
     XHQ E1.150: Hans/Jamie Overall design: Amsterdam plan / BinderHub /
     role of portal plan, milestones
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     XHQ E2.148: Detailed Q&A and hands-on session: Notebooks on HPC
     clusters? [Michael Schuh, Johannes Reppin]
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     XHQ E2.037: Detailed Q&A and hands-on session: Workflows -
     CWL/tools/dependencies/...? [Michael Crusoe]
   #+END_QUOTE

   -  

      #+BEGIN_QUOTE
        [[https://www.commonwl.org/user_guide/][/https://www.commonwl.org/user\_guide//]]
      #+END_QUOTE

   -  

      #+BEGIN_QUOTE
        [[https://toil.readthedocs.io/en/latest/running/hpcEnvironments.html?highlight=slurm][/https://toil.readthedocs.io/en/latest/running/hpcEnvironments.html?highlight=slurm/]]
      #+END_QUOTE

   -  

      #+BEGIN_QUOTE
        [[https://github.com/common-workflow-language/cwltool#leveraging-softwarerequirements-beta][/https://github.com/common-workflow-language/cwltool#leveraging-softwarerequirements-beta/]]
        How to use “module load” or conda instead of Docker containers
      #+END_QUOTE

   -  

      #+BEGIN_QUOTE
        Robert Rosca got toil-cwl-runner to submit SLURM jobs to Desy's
        Maxwell cluster.
      #+END_QUOTE

   -  

      #+BEGIN_QUOTE
        virtualenv -p python3 env3
      #+END_QUOTE

   -  

      #+BEGIN_QUOTE
        . env3/bin/activate
      #+END_QUOTE

   -  

      #+BEGIN_QUOTE
        pip install toil[cwl]
      #+END_QUOTE

   -  

      #+BEGIN_QUOTE
        TMPDIR=$HOME TOIL\_SLURM\_ARGS='--partition=exfel'
        toil-cwl-runner
        [[https://github.com/common-workflow-language/user_guide/raw/gh-pages/_includes/cwl/02-1st-example/1st-tool.cwl][/https://github.com/common-workflow-language/user\_guide/raw/gh-pages/\_includes/cwl/02-1st-example/1st-tool.cwl/]]
        [[https://github.com/common-workflow-language/user_guide/raw/gh-pages/_includes/cwl/02-1st-example/echo-job.yml][/https://github.com/common-workflow-language/user\_guide/raw/gh-pages/\_includes/cwl/02-1st-example/echo-job.yml/]]
      #+END_QUOTE

   -  
   -  

      #+BEGIN_QUOTE
        M. Crusoe proposes a project to expose a Jupyter Notebook to a
        CWL runner seamlessly
      #+END_QUOTE

-  

   #+BEGIN_QUOTE
     ?
   #+END_QUOTE

Further ideas for break out groups:

-  

   #+BEGIN_QUOTE
     Use case discussions and finalisation
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     Improving Jupyter ecosystem [Robert Rosca]
   #+END_QUOTE

   -  

      #+BEGIN_QUOTE
        Reproducibility, plotting, dashboards, interactivity
      #+END_QUOTE

Ideas(?) for tasks

-  

   #+BEGIN_QUOTE
     Put our software into pandata software catalog
   #+END_QUOTE

* --------------------------------------------------------
  :PROPERTIES:
  :CUSTOM_ID: section-1
  :END:

* Notes from break out groups
  :PROPERTIES:
  :CUSTOM_ID: notes-from-break-out-groups
  :END:

** Design discussion:
   :PROPERTIES:
   :CUSTOM_ID: design-discussion
   :END:

-  

   #+BEGIN_QUOTE
     Jacub Grosz, Michael Crusoe, Stuart, Giuseppe, Jamie, Gareth, Hans
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     Sandstorm.io
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     Other terms for portal: science gateway, virtual research
     environment :
   #+END_QUOTE

   -  

      #+BEGIN_QUOTE
        Conference in November Science September 23 to 25 in San Diego,
        sciencegateways.org
      #+END_QUOTE

   -  

      #+BEGIN_QUOTE
        Openscience foundation - combine data sources (osf.io)
      #+END_QUOTE

-  

   #+BEGIN_QUOTE
     *Portal*
   #+END_QUOTE

   -  

      #+BEGIN_QUOTE
        Only one (not WP3 and WP4 separately)
      #+END_QUOTE

   -  

      #+BEGIN_QUOTE
        Select data set from proposal
      #+END_QUOTE

      -  

         #+BEGIN_QUOTE
           Ideally based on experiment type (work out from NEXUS
           experiment type)
         #+END_QUOTE

      -  

         #+BEGIN_QUOTE
           Or offer all analysis tools used at that facility, ordered by
           instrument (hierarchical)
         #+END_QUOTE

   -  

      #+BEGIN_QUOTE
        Have suggestion of data analysis environment / templates
      #+END_QUOTE

   -  

      #+BEGIN_QUOTE
        Fire up analysis environments
      #+END_QUOTE

      -  

         #+BEGIN_QUOTE
           Either as independent browser tabs, or integrated into portal
           tab
         #+END_QUOTE

   -  

      #+BEGIN_QUOTE
        Nice to have:
      #+END_QUOTE

      -  

         #+BEGIN_QUOTE
           Display links to active analysis sessions
         #+END_QUOTE

      -  

         #+BEGIN_QUOTE
           Chat to allow users from the same experiment to communicate
         #+END_QUOTE

   -  

      #+BEGIN_QUOTE
        Jakub might produce some mock-ups
      #+END_QUOTE

   -  

      #+BEGIN_QUOTE
        Milestones: ?
      #+END_QUOTE

-  

   #+BEGIN_QUOTE
     *Discussion*
   #+END_QUOTE

   -  

      #+BEGIN_QUOTE
        Might be a delay in accessing data if data has been archived
        already
      #+END_QUOTE

      -  

         #+BEGIN_QUOTE
           Should communicate this to users: displayed message, sent
           email
         #+END_QUOTE

   -  

      #+BEGIN_QUOTE
        Use microservices to avoid building monolithic application
      #+END_QUOTE

-  

   #+BEGIN_QUOTE
     To be written up
   #+END_QUOTE

   -  

      #+BEGIN_QUOTE
        Amsterdam model, discussed with notebooks
      #+END_QUOTE

   -  

      #+BEGIN_QUOTE
        Milestone 1:
      #+END_QUOTE

      -  

         #+BEGIN_QUOTE
           analysis in facility specific notebook (it is okay if this
           only works at the originating facility)
         #+END_QUOTE

      -  

         #+BEGIN_QUOTE
           starting from some (facility-specific) data set
         #+END_QUOTE

      -  

         #+BEGIN_QUOTE
           small and public would be useful
         #+END_QUOTE

      -  

         #+BEGIN_QUOTE
           doing some analysis operation (python preferred) on this to
         #+END_QUOTE

      -  

         #+BEGIN_QUOTE
           create a figure/table/number of interest to scientists
         #+END_QUOTE

      -  

         #+BEGIN_QUOTE
           integrate scientists - we will need to use this analysis to
           attract them later to test and use the services
         #+END_QUOTE

   -  

      #+BEGIN_QUOTE
        Milestone 2:
      #+END_QUOTE

      -  

         #+BEGIN_QUOTE
           Create BinderHub instances at each facility
         #+END_QUOTE

      -  

         #+BEGIN_QUOTE
           Translate the facility specific Jupyter Notebook (from
           Milestone 1) to execute in the BinderHub environment. This
           requires specification of compute environment via Binder
           style environment specification
         #+END_QUOTE

      -  

         #+BEGIN_QUOTE
           put this specification and analysis notebook into some
           repository (github or local facility repo or else...)
         #+END_QUOTE

      -  

         #+BEGIN_QUOTE
           Point BinderHub to that repository
         #+END_QUOTE

      -  

         #+BEGIN_QUOTE
           The facility specific notebook should now execute via
           BinderHub at the facility
         #+END_QUOTE

      -  

         #+BEGIN_QUOTE
           the computer environment is in a container
         #+END_QUOTE

      -  

         #+BEGIN_QUOTE
           This software environment is facility-independent!
         #+END_QUOTE

      -  

         #+BEGIN_QUOTE
           However, data access will have to use some facility specific
           method
         #+END_QUOTE

   -  

      #+BEGIN_QUOTE
        Milestone 3:
      #+END_QUOTE

      -  

         #+BEGIN_QUOTE
           find a facility independent way to describe the data source
         #+END_QUOTE

         -  

            #+BEGIN_QUOTE
              analog to Binder software requirements, these are data
              requirements
            #+END_QUOTE

         -  

            #+BEGIN_QUOTE
              it is unclear how to do that
            #+END_QUOTE

         -  

            #+BEGIN_QUOTE
              if data sets are typically kept only by the facility they
              originate from, maybe it is okay if the data set locator
              specification is facility specific (such as
              EuXFEL/v1/p2222/r0013)?
            #+END_QUOTE

      -  

         #+BEGIN_QUOTE
           Find a way to bring that data to the compute location (or
           vice versa):
         #+END_QUOTE

         -  

            #+BEGIN_QUOTE
              Start with small example data sets (can wget them
              initially?)
            #+END_QUOTE

         -  

            #+BEGIN_QUOTE
              Could we move (public) example data sets to the 1PB STFC
              (?) storage space we have for demonstrators?
            #+END_QUOTE

         -  

            #+BEGIN_QUOTE
              At some point, use file transfer capabilities created in
              pilot in WP6.3 to access remote data
            #+END_QUOTE

         -  

            #+BEGIN_QUOTE
              From discussion at meeting: ONEDATA seems a good vehicle?
            #+END_QUOTE

            -  

               #+BEGIN_QUOTE
                 EGI Notebooks support it
               #+END_QUOTE

      -  

         #+BEGIN_QUOTE
           At this point, we should have (some) use cases that can
           execute on any PaNOSC facility and/or the EOSCHub, fetching
           data on demand
         #+END_QUOTE

-  

   #+BEGIN_QUOTE
     *More discussion (tomorrow)*
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     Resource management / API
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     DAta analysis needing lots of RAM / hardware requirements
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     Amsterdam model with VISA?
   #+END_QUOTE

*MILESTONE: User interface design (=Portal), 3 months, Jakub + Gareth +
Stuart + Jamie*

-  

   #+BEGIN_QUOTE
     What does the portal look like?
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     Possible workflows
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     Allow to start analysis part of workflow without search metadata
     catalog
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     Offer simulation tools from WP5 as ‘virtual data sets' that can be
     created by running the simulation
   #+END_QUOTE

List of milestones:

MILESTONE: Oct 2019 Sample jupyter notebooks (Thomas+Robert)

MILESTONE: Nov 2019 User interface design (portal), (Jakub + Gareth +
Stuart + Jamie)

MILESTONE: Feb 2020 Architecture selection of required technologies and
specification (Stuart+Eduard+Aidan)

MILESTONE: Mar 2020 Compute resources API specification (Stuart+Jamie)

MILESTONE: Jun 2020 Sample Remote desktop with local data (Stuart +
Jamie, VISA)

MILESTONE: Jun 2020 Sample Jupyter Notebooks execute in
BinderEnvironment with local data (Robert+Thomas)

MILESTONE: Oct 2020 Prototype implementation for portal (Carlos + Eduard
+ Jamie)

-  

   #+BEGIN_QUOTE
     Must seek feedback from users
   #+END_QUOTE

MILESTONE: February 2021 Sample Jupyter Notebooks execute in
BinderEnvironment with remote data (Thomas+Robert+Jamie)

MILESTONE: Mar 2021 Launch Remote Desktop and Jupyter analysis from
Portal (Eduard)

-  

   #+BEGIN_QUOTE
     Need metadata catalog to be searchable at this point -> align with
     WP3
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     WP3 demonstrator: scheduled for March 2021
   #+END_QUOTE

MILESTONE: Nov 2021 Demonstrator prototype completed (Eduard + Robert +
Jamie + Thomas)

MILESTONE: Nov 2021 First iteration of Documentation/Training materials
(Kareem + Thomas) [Python training in Jupyter, particular analysis for
selected analysis types, ...]

MILESTONE: May 2021, Obtained user feedback after beta testing /
validation (Thomas)

MILESTONE: Nov 2022, Deliverable 4.4

Check: cross check and link with tasks/deliverables in WP3, WP6, WP5,
WP8

WP4 Deliverables (from page 65 of proposal)

-  

   #+BEGIN_QUOTE
     Deliverable 4.1. Report on the current technical elements of data
     analysis at each partner site (M12 -> Nov 2019, R, PU, ILL)
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     Deliverable 4.2. Prototype remote desktop and Jupyter service (M18
     -> May 2020, DEM, CO, ILL)
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     Deliverable 4.3. Remote desktop and Jupyter analysis service
     deployed at EOSC (M42 -> May 2022, DEM, CO, XFEL.EU)
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     Deliverable 4.4. Publicly accessible demonstrator (M48 -> Nov 2022,
     DEM, PU, CERIC-ERIC)
   #+END_QUOTE

Future ideas/features:

-  

   #+BEGIN_QUOTE
     Chat/sharing/collaboration microservice (?)
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     Quota system microservice (to be discussed)
   #+END_QUOTE

*Architecture*

-  

   #+BEGIN_QUOTE
     What microservices
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     Deploy microservices through containers?
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     How do we integrate binderhub/Jupyterhub
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     Remote desktop websocket) microservice
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     Kafka message queue
   #+END_QUOTE

-  

*Required APIs*

-  

   #+BEGIN_QUOTE
     Authentication (WP6, Task 6.4) - to obtain token; Jamie to work
     with WP6
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     Catalog (WP3) - to retrieve embargoed proposals needs token / to
     search open data
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     MILESTONE Compute resources API specification, complete before
     annual meeting, Stuart + Jamie
   #+END_QUOTE

#+BEGIN_QUOTE
  - to request compute resources (potentially at other sites / in the
  cloud), to show current use,
#+END_QUOTE

*Experiment classification*

-  

   #+BEGIN_QUOTE
     Scientific experiment type ontology to suggest appropriate analysis
     steps
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     Develop and use this for a selected set of data (showcases)
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     Allow users to choose any data analysis environment, but aim to
     suggest likely sensible ones where possible. Could base suggestions
     on beamline, or on statistics of past usage.
   #+END_QUOTE

*Required outcomes from meeting*

-  

   #+BEGIN_QUOTE
     Internal milestones:
   #+END_QUOTE

   -  

      #+BEGIN_QUOTE
        What do we want to achieve
      #+END_QUOTE

   -  

      #+BEGIN_QUOTE
        By when
      #+END_QUOTE

   -  

      #+BEGIN_QUOTE
        Who is in charge (not to do the work exclusively themselves, but
        to ensure it is done)
      #+END_QUOTE

** Visualisation break out group
   :PROPERTIES:
   :CUSTOM_ID: visualisation-break-out-group
   :END:

-  

   #+BEGIN_QUOTE
     Unstructured discussions
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     Generic h5 viewer is needed
   #+END_QUOTE

   -  

      #+BEGIN_QUOTE
        Multiple concurrent activities underway
      #+END_QUOTE

-  

   #+BEGIN_QUOTE
     Could work with Jupyter Lab
   #+END_QUOTE

** JupyterHub Deployment
   :PROPERTIES:
   :CUSTOM_ID: jupyterhub-deployment
   :END:

-  

   #+BEGIN_QUOTE
     Jupyter Hub deployment
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     CalipsoPlus deployment tutorial
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     Creating custom notebooks
   #+END_QUOTE

   -  

      #+BEGIN_QUOTE
        Created common notebook images
      #+END_QUOTE

   -  

      #+BEGIN_QUOTE
        Accessing data from the notebooks
      #+END_QUOTE

      -  

         #+BEGIN_QUOTE
           NFS, ?
         #+END_QUOTE

   -  

      #+BEGIN_QUOTE
        Permissions
      #+END_QUOTE

-  

   #+BEGIN_QUOTE
     Would be good to work together on visualisation capabilities
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     Trello board?
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     Function as a service, Kafka
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     Collaborate on docker container recipes
   #+END_QUOTE

-  

   #+BEGIN_QUOTE
     Ancible and jupyter jub
   #+END_QUOTE

------------------------------------------------------

*** WP4 site leads:
    :PROPERTIES:
    :CUSTOM_ID: wp4-site-leads
    :END:

-  

   #+BEGIN_QUOTE
     Thomas Vincent (ESRF), Jamie Hall (ILL), Robert Rosca (EuXFEL),
     Kareem [Lottie] (ESS), Carlos (CERIC-ERIC), Jakub (ELI), Giuseppe
     (EGI)
   #+END_QUOTE


